export const haikus: Haiku[] = [
  {
    text: "O-to-ño,\nho-jas de co-lor\nna-ran-ja",
    date: "2017-10-06",
    order: 0,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La ho-ja tiem-bla,\npor fin em-pie-za_a ca-er,\nlle-ga_el o-to-ño",
    date: "2017-10-06",
    order: 1,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La ca-la-ba-za,\ncre-ce_en el huer-to,fe-liz,\npron-to son-rei-rá.",
    date: "2017-10-06",
    order: 2,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El ár-bol\nmu-da las ho-jas,\ncan-sa-do",
    date: "2017-10-06",
    order: 3,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La lu-na ro-ja\nin-di-ca la lle-ga-da,\nfe-liz co-se-cha",
    date: "2017-10-06",
    order: 4,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La som-bra lar-ga\nse-ña-la_al frí-o nor-te,\nlos o-sos duer-men",
    date: "2017-10-06",
    order: 5,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "De no-che_el fue-go\ncre-pi-ta_en la ho-gue-ra,\nca-lien-ta_el a-mor",
    date: "2017-10-06",
    order: 6,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Oc-tu-bre,\npor qué no du-ras?\nqué-da-te",
    date: "2017-10-06",
    order: 7,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Es-pe-ra,\npron-to ca-e-rá\nla no-che",
    date: "2017-10-06",
    order: 8,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El ca-lor\nde tu com-pa-ñí-a\nme lle-na",
    date: "2017-10-06",
    order: 9,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La pre-sión\nso-bre mi pe-cho,\nme_a-ho-ga",
    date: "2017-10-06",
    order: 10,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Te-mo de-ci-dir\nme que-do sin op-cio-nes,\nde-ten-te tiem-po",
    date: "2017-10-06",
    order: 11,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El ri-a-chue-lo\nhu-yen-do del des-hie-lo\no-tro a-ño más.",
    date: "2017-10-06",
    order: 12,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Los ni-ños co-rren,\ndis-fra-za-dos de -mons-truos,\npron-to llo-ra-rán",
    date: "2017-10-06",
    order: 13,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Hu-ye_el ve-ra-no,\nju-nio tra-e-lo a-quí,\nno hay fu-tu-ro.",
    date: "2017-10-06",
    order: 14,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Frí-o_a-zul\nNu-bes dis-tan-tes,\nIn-vier-no",
    date: "2019-01-13",
    order: 15,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Des-can-sa\nla vi-da_a-ho-ra,\ntran-qui-la",
    date: "2019-01-13",
    order: 16,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Des-nu-do\nel ár-bol duer-me,\nvol-ve-rá?",
    date: "2019-01-13",
    order: 17,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El vue-lo ra-so\ndel pá-ja-ro_a-za-ba-che,\ngé-li-do cam-po",
    date: "2019-01-13",
    order: 18,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Pe-num-bra\ni-nun-da_el mon-te,\nlo_a-bra-za",
    date: "2019-01-13",
    order: 19,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La nie-ve\ncu-bre el bos-que\nca-no-so",
    date: "2019-01-13",
    order: 20,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El to-cón\nco-bi-ja vi-da\nque duer-me",
    date: "2019-01-13",
    order: 21,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El rí-o\nse de-ti-e-ne\na_es-pe-rar",
    date: "2019-01-13",
    order: 22,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Re-pi-que-te-o,\nla ven-ta-na_a-fi-nan-do\nsu ins-tru-men-to",
    date: "2019-01-13",
    order: 23,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La_a-ra-ña\nte-je su mun-do\nen se-da.",
    date: "2019-01-13",
    order: 24,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Un bro-te\nse_a-gi-ta_al vien-to,\nal na-cer.",
    date: "2019-01-13",
    order: 25,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La bri-sa\nin-cli-na_al ta-llo,\npor siem-pre.",
    date: "2019-01-13",
    order: 26,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Las lu-ciér-na-gas\ni-lu-mi-nan el bos-que,\nguí-an la no-che",
    date: "2019-01-13",
    order: 27,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Un a-gu-je-ro\nal que so-lo se en-tra,\nva-cuo es-pa-cio",
    date: "2019-01-13",
    order: 28,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La puer-ta\na-sus-ta des-de\ndos ca-ras",
    date: "2019-01-13",
    order: 29,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El vien-to\ndes-nu-da_al ár-bol,\nca-du-co",
    date: "2019-01-13",
    order: 30,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La llu-ví-a es,\nla mon-ta-ña fue y es,\nno de-jo hue-lla",
    date: "2019-01-13",
    order: 31,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La llu-via mo-ja\nlos lon-ge-vos ár-bo-les\nsép-ti-mo_o-to-ño",
    date: "2021-10-26",
    order: 32,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Hú-me-do rit-mo,\nho-jas flo-tan-do_en char-cos,\nfu-gaz o-to-ño",
    date: "2021-10-26",
    order: 33,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ro-ja luz\nal-ma des-nu-da,\nsols-ti-cio",
    date: "2022-06-21",
    order: 34,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La llu-via\ntrae tu re-cuer-do,\ntris-te-za",
    date: "2023-05-19",
    order: 35,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Los rí-os\nno se di-vi-den,\npor siem-pre",
    date: "2024-10-17",
    order: 36,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "aun-que per-pe-tua\nla ro-ca va cam-bian-do,\nfal-so des-ti-no",
    date: "2024-10-17",
    order: 37,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "se me-cen\nlos sua-ves tol-dos\nca-lien-tes",
    date: "2024-10-17",
    order: 38,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "so-le-dad,\na-mor y o-dio\no-to-ñal",
    date: "2024-10-17",
    order: 39,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "la ro-ca\nes-pe-ra quie-ta,\nen cal-ma",
    date: "2024-10-17",
    order: 40,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "el cam-bio\ntra-e con-si-go\nel do-lor",
    date: "2024-10-17",
    order: 41,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La_an-sie-dad\nso-bre mi pe-cho\nme_a-ho-ga",
    date: "2024-10-17",
    order: 42,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El ár-bol\nal per-der la_ho-ja\nse mue-re",
    date: "2024-10-17",
    order: 43,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Re-bro-ta\ntras un de-sas-tre,\nla vi-da",
    date: "2024-11-21",
    order: 44,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Los sen-ti-mien-tos\na-flo-ran den-tro de mí,\nbue-nos o ma-los",
    date: "2024-12-11",
    order: 45,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Las nu-bes\nsiem-pre ter-mi-nan\npor ir-se",
    date: "2024-12-30",
    order: 46,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Se rom-pen\nvie-jas pro-me-sas,\nex-tra-ño",
    date: "2024-12-30",
    order: 47,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "A-ho-ra\ncó-mo con-fí-o\nen na-die?",
    date: "2024-12-30",
    order: 48,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Sin lo_im-po-si-ble\nla res-pues-ta de-be_es-tar\nen lo_im-pro-ba-ble",
    date: "2024-12-30",
    order: 49,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Pue-de de-cir-se\nal no_e-le-gir su cau-ce,\nin-fe-liz a-gua?",
    date: "2024-12-31",
    order: 50,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Más due-le\ntu da-ga_al sa-lir,\nte quie-ro",
    date: "2024-12-31",
    order: 51,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Si_e-xis-te_al-gún dios\na-guar-da con pa-cien-cia\nnues-tra per-di-ción",
    date: "2024-12-31",
    order: 52,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "De-ses-pe-ran-za\nne-gro pe-sar in-ter-no\nllu-via to-rren-cial",
    date: "2024-12-31",
    order: 53,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Có-mo com-pren-der\nque tras gar-gan-tuo cam-bio\nto-do si-gue_i-gual",
    date: "2024-12-31",
    order: 54,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Un tra-to,\nlim-piad las mi-nas\nsed li-bres",
    date: "2024-12-31",
    order: 55,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mi-ro_a-trás\nin-a-ca-ba-do\nper-sis-to",
    date: "2025-01-01",
    order: 56,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Be-lle-za,\nes-tás tam-bién en\nel do-lor?",
    date: "2025-01-01",
    order: 57,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Es-ca-par\nde tu des-ti-no\nes men-tal",
    date: "2025-01-01",
    order: 58,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Pre-vio_a-mor\nya des-gas-ta-do,\na-mis-tad?",
    date: "2025-01-01",
    order: 59,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Me cuen-to\nmen-ti-ras pa-ra\ncre-er-las",
    date: "2025-01-01",
    order: 60,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Es-cue-tos\npo-e-mas di-cen\nla ver-dad?",
    date: "2025-01-01",
    order: 61,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Dón-de_es-tá\nel pro-pó-si-to\nde vi-vir?",
    date: "2025-01-01",
    order: 62,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "To-ca e-le-gir\nlas ver-da-des del nue-vo\ne_in-cier-to si-no",
    date: "2025-01-06",
    order: 63,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Tor-men-ta,\na-gi-ta_y_em-pu-ja\nmis ve-las",
    date: "2025-01-07",
    order: 64,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "E-xis-te\nre-al-men-te el\nfra-ca-so?",
    date: "2025-01-07",
    order: 65,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ás-pe-ro\ndo-lor dor-mi-ta\npor den-tro",
    date: "2025-01-07",
    order: 66,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El ar-te\na-pa-ga_el do-lor\nde mi_al-ma",
    date: "2025-01-07",
    order: 67,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Qui-én di-rí-a\nque_el al-ma_es-tá for-ma-da\npor tan-tas pie-zas?",
    date: "2025-01-07",
    order: 68,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Y si la vi-da\nno tie-ne más sen-ti-do\nque dis-fru-tar-la?",
    date: "2025-01-07",
    order: 69,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Me_han ro-to,\nde-pen-de de mí\nre-gre-sar",
    date: "2025-01-07",
    order: 70,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Se_a-ca-bó,\nfrí-a tris-te-za,\ndes-a-mor",
    date: "2025-01-07",
    order: 71,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La lu-na\nya no son-rí-e\npa-ra mí",
    date: "2025-01-07",
    order: 72,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Al fi-nal\nto-do_es la-men-to\ny pe-na",
    date: "2025-01-07",
    order: 73,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ya no se\nque es co-rrec-to\ny que no",
    date: "2025-01-10",
    order: 74,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Soy li-bre\npa-ra bien o mal\nyo man-do",
    date: "2025-01-13",
    order: 75,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Po-der e-le-gir\nmi com-ple-to des-ti-no\nal-ma des-nu-da",
    date: "2025-01-13",
    order: 76,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "To-dos sa-be-mos\nco-mo fun-cio-na to-do\nsi no_es-tá ro-to",
    date: "2025-01-17",
    order: 77,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Bien y mal\nes sub-je-ti-vo\ny fu-gaz",
    date: "2025-01-17",
    order: 78,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Cuan-do pre-gun-tes\nde-bes es-tar a-bier-to\na la res-pues-ta",
    date: "2025-01-19",
    order: 79,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mi_a-mi-go\nse fue por siem-pre,\ndos a-ños",
    date: "2025-01-23",
    order: 80,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El to-cón\npa-re-ce muer-to,\nes-pe-ra",
    date: "2025-01-28",
    order: 81,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Dí-as fu-ga-ces\ncie-los lle-nos de_es-tre-llas,\nbos-ques ne-va-dos",
    date: "2025-01-28",
    order: 82,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mar-te_y Ju-pi-ter\nNep-tu-no_U-ra-no_y Ve-nus,\ncie-lo ú-ni-co",
    date: "2025-01-28",
    order: 83,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ra-mas des-nu-das\ncie-los de to-nos gri-ses,\nfi-nal del ci-clo",
    date: "2025-01-28",
    order: 84,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Cie-lo co-bri-zo\nlas som-bras co-rren li-bres,\nlle-ga la no-che",
    date: "2025-01-28",
    order: 85,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "E-ter-no tic-tac\nsu-ce-si-ón in-fi-ni-ta,\nsen-ti-do fa-laz",
    date: "2025-01-28",
    order: 86,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ri-sas ner-vio-sas,\ndos a-man-tes dis-fru-tan\nes-tan-do jun-tos",
    date: "2025-01-28",
    order: 87,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "El pol-vo cu-bre\nlas te-clas de plás-ti-co,\ndes-ti-no co-mún",
    date: "2025-01-29",
    order: 88,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "U-na_al-mo-ha-da\ndon-de an-tes e-ran dos,\nsue-ño le-ja-no",
    date: "2025-01-29",
    order: 89,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "A-mi-go cuen-co\nto-ma-mos el té jun-tos,\nma-ña-nas frí-as",
    date: "2025-01-30",
    order: 90,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Cual lu-ciér-na-gas\na-lum-bran mi pa-se-o\nmi-les de lu-ces",
    date: "2025-01-30",
    order: 91,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Un des-per-fec-to\nen mi co-che cre-í ver,\nu-na po-li-lla",
    date: "2025-01-30",
    order: 92,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "In-di-fe-ren-tes,\ncán-ti-cos de go-rrio-nes\nen el in-vier-no",
    date: "2025-01-31",
    order: 93,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Na-tu-ra-le-za\ncu-bier-ta de as-fal-to,\nmu-sa nos-tal-gía",
    date: "2025-01-31",
    order: 94,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Tris-tes re-cuer-dos,\nre-loj re-ci-ta man-tra\nme-ce la no-che",
    date: "2025-02-01",
    order: 95,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Bri-sa he-la-da\ncá-li-do to-que de sol,\ndí-a in-ver-nal",
    date: "2025-02-01",
    order: 96,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "U-na u-rra-ca\nre-bus-ca en-tre res-tos,\n¡va-ya ban-que-te!",
    date: "2025-02-01",
    order: 97,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Gra-ta sor-pre-sa,\n¡u-na pa-ta-ta de-luxe\nen mi pe-di-do!",
    date: "2025-02-01",
    order: 98,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Vi-si-ta bre-ve,\ngo-rrión can-ta frus-tra-do\nvue-lo ham-brien-to",
    date: "2025-02-01",
    order: 99,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Sien-to en-vi-dia,\nar-tis-tas an-ces-tra-les\nque be-llos ver-sos",
    date: "2025-02-01",
    order: 100,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ba-jo tu som-bra\nes-pe-ro a las flo-res,\ngi-gan-te ver-de",
    date: "2025-02-05",
    order: 101,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Co-rro y co-rro\nper-si-go u-na me-ta,\nel ho-ri-zon-te",
    date: "2025-02-06",
    order: 102,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mi-ro_al o-es-te\nsor-pren-den-te be-lle-za,\no-ca-so ro-sa",
    date: "2025-02-06",
    order: 103,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Es-pe-sa nie-bla\npier-des al pe-re-gri-no,\n¿qué pro-pó-si-to?",
    date: "2025-02-07",
    order: 104,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "E-cos pa-sa-dos,\nes-pi-rí-tus pre-sen-tes,\nre-cuer-dos ro-tos",
    date: "2025-02-11",
    order: 105,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ba-jo es-tre-llas\nnues-tros re-cuer-dos jun-tos\nro-ban mi sue-ño",
    date: "2025-02-12",
    order: 106,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "To-dos los co-pos\na-ca-ban de-rre-ti-dos,\nman-to al-bi-no",
    date: "2025-02-18",
    order: 107,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mu-sa mo-nar-ca\n¿có-mo con-si-go ha-cer\nque no te va-yas?",
    date: "2025-02-18",
    order: 108,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "For-mas le-ja-nas\nbru-ma de las mon-ta-ñas\na-bri-go frí-o",
    date: "2025-02-20",
    order: 109,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Al-ta mon-ta-ña\nnu-bes cu-bren tu ci-ma\na-ho-ra pla-na",
    date: "2025-02-23",
    order: 110,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Vis-ta in-ver-nal\npi-ro-tec-nia ro-sa-da\nllu-via de_al-mendras",
    date: "2025-02-23",
    order: 111,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mi pa-so de-ja\nhue-llas en el ca-mi-no,\nque_el tiem-po bo-rra",
    date: "2025-02-25",
    order: 112,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Yer-mo pá-ra-mo,\nbro-te de-sa-fian-te\nvo-lun-tad sa-cra",
    date: "2025-02-26",
    order: 113,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Ex-tra-ño ár-bol,\nre-pa-so mi ca-mi-no\n¿Dón-de me per-dí?",
    date: "2025-02-27",
    order: 114,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Char-co de llu-via,\ne-fí-me-ro re-fle-jo\nllé-va-me a-llí",
    date: "2025-03-01",
    order: 115,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "La llu-via ca-e\nel ar-tis-ta es-cri-be\nel al-ma vi-ve",
    date: "2025-03-01",
    order: 116,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Sa-lí con mie-do\nmi-ran-do co-mo vol-ver,\ntiem-po de co-rrer",
    date: "2025-03-02",
    order: 117,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Lar-go ca-mi-nar,\nhu-mo con-tra el cie-lo,\npla-to ca-lien-te",
    date: "2025-03-02",
    order: 118,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "De vuel-ta en pie\nca-mi-no sin co-ge-ar,\nmás a-ún due-le",
    date: "2025-03-02",
    order: 119,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Pe-que-ño go-rrión,\n¿trae-rás las mis-mas plu-mas\ntras el ve-ra-no?",
    date: "2025-03-03",
    order: 120,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Du-ra ca-í-da,\na par-tir de a-ho-ra\nmi-ra tus bo-tas",
    date: "2025-03-03",
    order: 121,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Mo-ja-do_el sue-lo\nmar-zo trae_el e-qui-no-cio\nrít-mi-co ger-mén",
    date: "2025-03-05",
    order: 122,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "Sol y es-tre-llas\nper-fec-to e-qui-li-brio,\npuer-ta a-bier-ta",
    date: "2025-03-05",
    order: 123,
    selected: false,
    tags: [],
    hide: false,
  },
  {
    text: "¡Un ver-de-ci-llo!\nvi-si-ta pri-ma-ve-ral\nal-go tem-pra-na",
    date: "2025-03-10",
    order: 124,
    selected: true,
    tags: [],
    hide: false,
  },
  {
    text: "Tras tan-to tiem-po,\nes tu ho-ra de bri-llar\n¡suer-te a-mi-go!",
    date: "2025-03-10",
    order: 125,
    selected: false,
    tags: [],
    hide: false,
  },
];

export type Haiku = {
  text: string;
  date: string;
  selected: boolean;
  order: number;
  tags: string[];
  hide: boolean;
};
